/**
 * CSS 单位和数值类型定义
 * 自动生成，请勿手动修改
 */

// ==================== 数值类型名称 ====================

/** 角度值，以度 (deg)、百分度 (grad)、弧度 (rad) 或圈数 (turn) 表示。 */
export const ANGLE_NUMBER_TYPE_NAME = 'angle' as const;
/** 可以是 <angle> 或 <percentage> 的值。 */
export const ANGLE_PERCENTAGE_NUMBER_TYPE_NAME = 'angle-percentage' as const;
/** 弹性长度，以 fr 为单位，表示网格容器中剩余空间的分数。 */
export const FLEX_NUMBER_TYPE_NAME = 'flex' as const;
/** 频率值，以赫兹 (Hz) 或千赫兹 (kHz) 表示。 */
export const FREQUENCY_NUMBER_TYPE_NAME = 'frequency' as const;
/** 可以是 <frequency> 或 <percentage> 的值。 */
export const FREQUENCY_PERCENTAGE_NUMBER_TYPE_NAME = 'frequency-percentage' as const;
/** 整数，正数或负数。 */
export const INTEGER_NUMBER_TYPE_NAME = 'integer' as const;
/** 距离度量。表示长度值，如 px、em、rem、vh、vw 等。 */
export const LENGTH_NUMBER_TYPE_NAME = 'length' as const;
/** 可以是 <length> 或 <percentage> 的值。 */
export const LENGTH_PERCENTAGE_NUMBER_TYPE_NAME = 'length-percentage' as const;
/** 实数，可能带有小数部分。 */
export const NUMBER_NUMBER_TYPE_NAME = 'number' as const;
/** 百分比值。表示某个其他值的分数。 */
export const PERCENTAGE_NUMBER_TYPE_NAME = 'percentage' as const;
/** 分辨率值，用于描述输出设备的像素密度 (dpi、dpcm、dppx)。 */
export const RESOLUTION_NUMBER_TYPE_NAME = 'resolution' as const;
/** 时间值，以秒 (s) 或毫秒 (ms) 表示。 */
export const TIME_NUMBER_TYPE_NAME = 'time' as const;
/** 可以是 <time> 或 <percentage> 的值。 */
export const TIME_PERCENTAGE_NUMBER_TYPE_NAME = 'time-percentage' as const;

/** 所有数值类型名称 */
export const NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  ANGLE_PERCENTAGE_NUMBER_TYPE_NAME,
  FLEX_NUMBER_TYPE_NAME,
  FREQUENCY_NUMBER_TYPE_NAME,
  FREQUENCY_PERCENTAGE_NUMBER_TYPE_NAME,
  INTEGER_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
  RESOLUTION_NUMBER_TYPE_NAME,
  TIME_NUMBER_TYPE_NAME,
  TIME_PERCENTAGE_NUMBER_TYPE_NAME,
] as const;

/** 数值类型名称联合 */
export type NumberTypeName = typeof NUMBER_TYPES[number];

// ==================== 单位 ====================

/** 所有单位 */
export const ALL_UNITS = [
  '%',
  '<number>',
  'Hz',
  'Q',
  'cap',
  'ch',
  'cm',
  'deg',
  'dpcm',
  'dpi',
  'dppx',
  'dvh',
  'dvw',
  'em',
  'ex',
  'fr',
  'grad',
  'ic',
  'in',
  'kHz',
  'lh',
  'lvh',
  'lvw',
  'mm',
  'ms',
  'pc',
  'pt',
  'px',
  'rad',
  'rem',
  'rlh',
  's',
  'svh',
  'svw',
  'turn',
  'vb',
  'vh',
  'vi',
  'vmax',
  'vmin',
  'vw',
  'x',
] as const;

/** 单位类型 */
export type UnitType = typeof ALL_UNITS[number];

// ==================== 数值类型到单位映射 ====================

export const ANGLE_UNITS = [
  '%',
  '<number>',
  'Q',
  'cap',
  'ch',
  'cm',
  'deg',
  'dpcm',
  'dpi',
  'dppx',
  'dvh',
  'dvw',
  'em',
  'ex',
  'grad',
  'ic',
  'in',
  'lh',
  'lvh',
  'lvw',
  'mm',
  'pc',
  'pt',
  'px',
  'rad',
  'rem',
  'rlh',
  'svh',
  'svw',
  'turn',
  'vb',
  'vh',
  'vi',
  'vmax',
  'vmin',
  'vw',
  'x',
] as const;
export const ANGLE_PERCENTAGE_UNITS = [
  '%',
  '<number>',
  'Q',
  'cap',
  'ch',
  'cm',
  'deg',
  'dpcm',
  'dpi',
  'dppx',
  'dvh',
  'dvw',
  'em',
  'ex',
  'grad',
  'ic',
  'in',
  'lh',
  'lvh',
  'lvw',
  'mm',
  'pc',
  'pt',
  'px',
  'rad',
  'rem',
  'rlh',
  'svh',
  'svw',
  'turn',
  'vb',
  'vh',
  'vi',
  'vmax',
  'vmin',
  'vw',
  'x',
] as const;
export const FLEX_UNITS = [
  '%',
  '<number>',
  'Q',
  'cap',
  'ch',
  'cm',
  'dvh',
  'dvw',
  'em',
  'ex',
  'fr',
  'ic',
  'in',
  'lh',
  'lvh',
  'lvw',
  'mm',
  'pc',
  'pt',
  'px',
  'rem',
  'rlh',
  'svh',
  'svw',
  'vb',
  'vh',
  'vi',
  'vmax',
  'vmin',
  'vw',
] as const;
export const FREQUENCY_UNITS = [
  '%',
  'Hz',
  'kHz',
] as const;
export const FREQUENCY_PERCENTAGE_UNITS = [
] as const;
export const INTEGER_UNITS = [
  '%',
  '<number>',
  'Q',
  'cap',
  'ch',
  'cm',
  'dvh',
  'dvw',
  'em',
  'ex',
  'fr',
  'ic',
  'in',
  'lh',
  'lvh',
  'lvw',
  'mm',
  'ms',
  'pc',
  'pt',
  'px',
  'rem',
  'rlh',
  's',
  'svh',
  'svw',
  'vb',
  'vh',
  'vi',
  'vmax',
  'vmin',
  'vw',
] as const;
export const LENGTH_UNITS = [
  '%',
  '<number>',
  'Q',
  'cap',
  'ch',
  'cm',
  'deg',
  'dpcm',
  'dpi',
  'dppx',
  'dvh',
  'dvw',
  'em',
  'ex',
  'fr',
  'grad',
  'ic',
  'in',
  'lh',
  'lvh',
  'lvw',
  'mm',
  'pc',
  'pt',
  'px',
  'rad',
  'rem',
  'rlh',
  'svh',
  'svw',
  'turn',
  'vb',
  'vh',
  'vi',
  'vmax',
  'vmin',
  'vw',
  'x',
] as const;
export const LENGTH_PERCENTAGE_UNITS = [
  '%',
  '<number>',
  'Q',
  'cap',
  'ch',
  'cm',
  'deg',
  'dpcm',
  'dpi',
  'dppx',
  'dvh',
  'dvw',
  'em',
  'ex',
  'fr',
  'grad',
  'ic',
  'in',
  'lh',
  'lvh',
  'lvw',
  'mm',
  'pc',
  'pt',
  'px',
  'rad',
  'rem',
  'rlh',
  'svh',
  'svw',
  'turn',
  'vb',
  'vh',
  'vi',
  'vmax',
  'vmin',
  'vw',
  'x',
] as const;
export const NUMBER_UNITS = [
  '%',
  '<number>',
  'Q',
  'cap',
  'ch',
  'cm',
  'deg',
  'dpcm',
  'dpi',
  'dppx',
  'dvh',
  'dvw',
  'em',
  'ex',
  'grad',
  'ic',
  'in',
  'lh',
  'lvh',
  'lvw',
  'mm',
  'ms',
  'pc',
  'pt',
  'px',
  'rad',
  'rem',
  'rlh',
  's',
  'svh',
  'svw',
  'turn',
  'vb',
  'vh',
  'vi',
  'vmax',
  'vmin',
  'vw',
  'x',
] as const;
export const PERCENTAGE_UNITS = [
  '%',
  '<number>',
  'Hz',
  'Q',
  'cap',
  'ch',
  'cm',
  'deg',
  'dpcm',
  'dpi',
  'dppx',
  'dvh',
  'dvw',
  'em',
  'ex',
  'fr',
  'grad',
  'ic',
  'in',
  'kHz',
  'lh',
  'lvh',
  'lvw',
  'mm',
  'pc',
  'pt',
  'px',
  'rad',
  'rem',
  'rlh',
  'svh',
  'svw',
  'turn',
  'vb',
  'vh',
  'vi',
  'vmax',
  'vmin',
  'vw',
  'x',
] as const;
export const RESOLUTION_UNITS = [
  '%',
  '<number>',
  'Q',
  'cap',
  'ch',
  'cm',
  'deg',
  'dpcm',
  'dpi',
  'dppx',
  'dvh',
  'dvw',
  'em',
  'ex',
  'grad',
  'ic',
  'in',
  'lh',
  'lvh',
  'lvw',
  'mm',
  'pc',
  'pt',
  'px',
  'rad',
  'rem',
  'rlh',
  'svh',
  'svw',
  'turn',
  'vb',
  'vh',
  'vi',
  'vmax',
  'vmin',
  'vw',
  'x',
] as const;
export const TIME_UNITS = [
  '<number>',
  'ms',
  's',
] as const;
export const TIME_PERCENTAGE_UNITS = [
] as const;

/** 数值类型到单位的映射 */
export const NUMBER_TYPE_UNITS = {
  'angle': ANGLE_UNITS,
  'angle-percentage': ANGLE_PERCENTAGE_UNITS,
  'flex': FLEX_UNITS,
  'frequency': FREQUENCY_UNITS,
  'frequency-percentage': FREQUENCY_PERCENTAGE_UNITS,
  'integer': INTEGER_UNITS,
  'length': LENGTH_UNITS,
  'length-percentage': LENGTH_PERCENTAGE_UNITS,
  'number': NUMBER_UNITS,
  'percentage': PERCENTAGE_UNITS,
  'resolution': RESOLUTION_UNITS,
  'time': TIME_UNITS,
  'time-percentage': TIME_PERCENTAGE_UNITS,
} as const;

// ==================== 属性数值类型 ====================

export const ACCENT_COLOR_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const ANIMATION_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const ANIMATION_DELAY_NUMBER_TYPES = [
  TIME_NUMBER_TYPE_NAME,
] as const;
export const ANIMATION_DURATION_NUMBER_TYPES = [
  TIME_NUMBER_TYPE_NAME,
] as const;
export const ANIMATION_ITERATION_COUNT_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const ANIMATION_RANGE_END_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const ANIMATION_RANGE_START_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const ANIMATION_TIMING_FUNCTION_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const ASPECT_RATIO_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const AZIMUTH_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
] as const;
export const BACKDROP_FILTER_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BACKGROUND_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  ANGLE_PERCENTAGE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
  RESOLUTION_NUMBER_TYPE_NAME,
] as const;
export const BACKGROUND_COLOR_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BACKGROUND_IMAGE_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  ANGLE_PERCENTAGE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
  RESOLUTION_NUMBER_TYPE_NAME,
] as const;
export const BACKGROUND_POSITION_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BACKGROUND_POSITION_X_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BACKGROUND_POSITION_Y_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BACKGROUND_SIZE_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BASELINE_SHIFT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_BLOCK_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_BLOCK_END_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_BLOCK_START_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_BOTTOM_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_BOTTOM_LEFT_RADIUS_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_BOTTOM_RIGHT_RADIUS_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_BOTTOM_WIDTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const BORDER_COLOR_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_END_END_RADIUS_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_END_START_RADIUS_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_IMAGE_OUTSET_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const BORDER_IMAGE_SLICE_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_IMAGE_SOURCE_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  ANGLE_PERCENTAGE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
  RESOLUTION_NUMBER_TYPE_NAME,
] as const;
export const BORDER_IMAGE_WIDTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_INLINE_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_INLINE_END_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_INLINE_START_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_LEFT_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_LEFT_COLOR_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_LEFT_WIDTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const BORDER_RADIUS_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_RIGHT_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_RIGHT_COLOR_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_RIGHT_WIDTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const BORDER_SPACING_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const BORDER_START_END_RADIUS_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_START_START_RADIUS_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_TOP_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_TOP_COLOR_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_TOP_LEFT_RADIUS_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_TOP_RIGHT_RADIUS_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BORDER_TOP_WIDTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const BORDER_WIDTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const BOTTOM_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const BOX_FLEX_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const BOX_FLEX_GROUP_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const BOX_ORDINAL_GROUP_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const BOX_SHADOW_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const CARET_COLOR_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const CLIP_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const CLIP_PATH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const COLOR_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const COLUMN_COUNT_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const COLUMN_GAP_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const COLUMN_RULE_COLOR_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const COLUMN_WIDTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const CONTAIN_INTRINSIC_BLOCK_SIZE_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const CONTAIN_INTRINSIC_HEIGHT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const CONTAIN_INTRINSIC_INLINE_SIZE_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const CONTAIN_INTRINSIC_SIZE_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const CONTAIN_INTRINSIC_WIDTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const CONTENT_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  ANGLE_PERCENTAGE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
  RESOLUTION_NUMBER_TYPE_NAME,
] as const;
export const COUNTER_INCREMENT_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const COUNTER_RESET_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const COUNTER_SET_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const CURSOR_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const CX_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const CY_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const FILL_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const FILL_OPACITY_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const FILTER_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const FLEX_GROW_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const FLEX_SHRINK_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const FONT_FEATURE_SETTINGS_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const FONT_SIZE_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const FONT_SIZE_ADJUST_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const FONT_SMOOTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const FONT_STRETCH_NUMBER_TYPES = [
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const FONT_STYLE_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
] as const;
export const FONT_VARIATION_SETTINGS_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const FONT_WEIGHT_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const GLYPH_ORIENTATION_HORIZONTAL_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
] as const;
export const GLYPH_ORIENTATION_VERTICAL_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
] as const;
export const GRID_AREA_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const GRID_AUTO_COLUMNS_NUMBER_TYPES = [
  FLEX_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const GRID_AUTO_ROWS_NUMBER_TYPES = [
  FLEX_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const GRID_COLUMN_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const GRID_COLUMN_END_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const GRID_COLUMN_GAP_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const GRID_COLUMN_START_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const GRID_ROW_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const GRID_ROW_END_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const GRID_ROW_GAP_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const GRID_ROW_START_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const GRID_TEMPLATE_NUMBER_TYPES = [
  FLEX_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const GRID_TEMPLATE_COLUMNS_NUMBER_TYPES = [
  FLEX_NUMBER_TYPE_NAME,
  INTEGER_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const GRID_TEMPLATE_ROWS_NUMBER_TYPES = [
  FLEX_NUMBER_TYPE_NAME,
  INTEGER_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const HEIGHT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const HYPHENATE_LIMIT_CHARS_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const IMAGE_ORIENTATION_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
] as const;
export const IMAGE_RESOLUTION_NUMBER_TYPES = [
  RESOLUTION_NUMBER_TYPE_NAME,
] as const;
export const INITIAL_LETTER_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const KERNING_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const LEFT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const LETTER_SPACING_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const LINE_CLAMP_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const LINE_HEIGHT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const LINE_HEIGHT_STEP_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const LIST_STYLE_IMAGE_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  ANGLE_PERCENTAGE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
  RESOLUTION_NUMBER_TYPE_NAME,
] as const;
export const MARGIN_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const MARGIN_BOTTOM_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const MARGIN_LEFT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const MARGIN_RIGHT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const MARGIN_TOP_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const MASK_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  ANGLE_PERCENTAGE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
  RESOLUTION_NUMBER_TYPE_NAME,
] as const;
export const MASK_BORDER_OUTSET_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const MASK_BORDER_SLICE_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const MASK_BORDER_SOURCE_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  ANGLE_PERCENTAGE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
  RESOLUTION_NUMBER_TYPE_NAME,
] as const;
export const MASK_BORDER_WIDTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const MASK_IMAGE_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  ANGLE_PERCENTAGE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
  RESOLUTION_NUMBER_TYPE_NAME,
] as const;
export const MASK_POSITION_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const MASK_SIZE_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const MATH_DEPTH_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const MAX_HEIGHT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const MAX_LINES_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const MAX_WIDTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const MIN_HEIGHT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const MIN_WIDTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const OBJECT_POSITION_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const OFFSET_ANCHOR_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const OFFSET_DISTANCE_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const OFFSET_PATH_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const OFFSET_POSITION_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const OFFSET_ROTATE_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
] as const;
export const OPACITY_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const ORDER_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const ORPHANS_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const OUTLINE_COLOR_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const OUTLINE_OFFSET_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const OUTLINE_WIDTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const OVERFLOW_CLIP_MARGIN_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const PADDING_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const PADDING_BOTTOM_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const PADDING_LEFT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const PADDING_RIGHT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const PADDING_TOP_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const PAUSE_AFTER_NUMBER_TYPES = [
  TIME_NUMBER_TYPE_NAME,
] as const;
export const PAUSE_BEFORE_NUMBER_TYPES = [
  TIME_NUMBER_TYPE_NAME,
] as const;
export const PERSPECTIVE_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const PERSPECTIVE_ORIGIN_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const R_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const REST_AFTER_NUMBER_TYPES = [
  TIME_NUMBER_TYPE_NAME,
] as const;
export const REST_BEFORE_NUMBER_TYPES = [
  TIME_NUMBER_TYPE_NAME,
] as const;
export const RIGHT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const ROTATE_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const ROW_GAP_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const RX_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const RY_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCALE_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_MARGIN_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_MARGIN_BLOCK_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_MARGIN_BLOCK_END_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_MARGIN_BLOCK_START_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_MARGIN_BOTTOM_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_MARGIN_INLINE_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_MARGIN_INLINE_END_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_MARGIN_INLINE_START_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_MARGIN_LEFT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_MARGIN_RIGHT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_MARGIN_TOP_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_PADDING_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_PADDING_BLOCK_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_PADDING_BLOCK_END_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_PADDING_BLOCK_START_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_PADDING_BOTTOM_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_PADDING_INLINE_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_PADDING_INLINE_END_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_PADDING_INLINE_START_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_PADDING_LEFT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_PADDING_RIGHT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_PADDING_TOP_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_SNAP_COORDINATE_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_SNAP_DESTINATION_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_SNAP_POINTS_X_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLL_SNAP_POINTS_Y_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SCROLLBAR_COLOR_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SHAPE_IMAGE_THRESHOLD_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SHAPE_MARGIN_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const SHAPE_OUTSIDE_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  ANGLE_PERCENTAGE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
  RESOLUTION_NUMBER_TYPE_NAME,
] as const;
export const STROKE_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const STROKE_DASHARRAY_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const STROKE_DASHOFFSET_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const STROKE_MITERLIMIT_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const STROKE_WIDTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const TAB_SIZE_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const TEXT_COMBINE_UPRIGHT_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const TEXT_DECORATION_COLOR_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const TEXT_DECORATION_THICKNESS_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const TEXT_EMPHASIS_COLOR_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const TEXT_INDENT_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const TEXT_SHADOW_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const TEXT_SIZE_ADJUST_NUMBER_TYPES = [
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const TEXT_UNDERLINE_OFFSET_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const TOP_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const TRANSFORM_NUMBER_TYPES = [
  ANGLE_NUMBER_TYPE_NAME,
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const TRANSFORM_ORIGIN_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const TRANSITION_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
  TIME_NUMBER_TYPE_NAME,
] as const;
export const TRANSITION_DELAY_NUMBER_TYPES = [
  TIME_NUMBER_TYPE_NAME,
] as const;
export const TRANSITION_DURATION_NUMBER_TYPES = [
  TIME_NUMBER_TYPE_NAME,
] as const;
export const TRANSITION_TIMING_FUNCTION_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const TRANSLATE_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const VERTICAL_ALIGN_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const VIEW_TIMELINE_INSET_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const VOICE_BALANCE_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
] as const;
export const VOICE_DURATION_NUMBER_TYPES = [
  TIME_NUMBER_TYPE_NAME,
] as const;
export const VOICE_FAMILY_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const VOICE_PITCH_NUMBER_TYPES = [
  FREQUENCY_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const VOICE_RANGE_NUMBER_TYPES = [
  FREQUENCY_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const VOICE_RATE_NUMBER_TYPES = [
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const WIDOWS_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const WIDTH_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  LENGTH_PERCENTAGE_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const WORD_SPACING_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
] as const;
export const X_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const Y_NUMBER_TYPES = [
  LENGTH_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
export const Z_INDEX_NUMBER_TYPES = [
  INTEGER_NUMBER_TYPE_NAME,
] as const;
export const ZOOM_NUMBER_TYPES = [
  NUMBER_NUMBER_TYPE_NAME,
  PERCENTAGE_NUMBER_TYPE_NAME,
] as const;
