/**
 * 预设配置导出
 */

export {
  CORE_PROPERTIES,
  RARE_PROPERTIES,
  TAILWIND_SPACING_SCALE,
  TAILWIND_SPACING_PX,
  TAILWIND_PERCENTAGES,
  TAILWIND_REM_VALUES,
  TAILWIND_OPACITY_VALUES,
  TAILWIND_ZINDEX_VALUES,
  TAILWIND_BORDER_RADIUS,
  TAILWIND_FONT_SIZES,
  TAILWIND_FONT_WEIGHTS,
  TAILWIND_LINE_HEIGHTS,
  TAILWIND_LETTER_SPACINGS,
  TAILWIND_LIKE_PRESET,
} from './tailwind-like';
