// Auto-generated by cssts
// Do not edit manually

/** CSS class 对象类型 */
type CssClassObj = { readonly [key: string]: true }

export interface CssCls {
}

declare const CssCls: CssCls
export default CssCls