// Auto-generated by cssts
// Do not edit manually

export const CssCls = {
} as const

export default CssCls

// 类型定义
export type CssClsKey = keyof typeof CssCls
export type CssClsValue = typeof CssCls[CssClsKey]