// Auto-generated by vite-plugin-cssts
// Do not edit manually

import type { CsstsAtoms } from 'cssts-types'

/**
 * CsstsAtom 实现类
 * 包含项目中使用的所有原子类
 */
class CsstsAtomImpl implements Partial<CsstsAtoms> {
  readonly alignItemsCenter = { 'align-items-center': true } as const
  readonly backgroundColorBlue500 = { 'background-color-blue-500': true } as const
  readonly backgroundColorGreen500 = { 'background-color-green-500': true } as const
  readonly backgroundColorWhite = { 'background-color-white': true } as const
  readonly colorGray700 = { 'color-gray-700': true } as const
  readonly colorWhite = { 'color-white': true } as const
  readonly displayInlineFlex = { 'display-inline-flex': true } as const
  readonly justifyContentCenter = { 'justify-content-center': true } as const
}

/** 原子类实例 */
export const csstsAtom = new CsstsAtomImpl()

export default csstsAtom