/**
 * CsstsAtoms 接口 - 原子类类型定义
 *
 * 自动生成，请勿手动修改
 * 生成时间: 2025-12-18T17:01:24.044Z
 */

export interface CsstsAtoms {
  // ==================== top ====================
  readonly topAuto: { 'top_auto': true }
  readonly top0Q: { 'top_0Q': true }
  readonly top1Q: { 'top_1Q': true }
  readonly top2Q: { 'top_2Q': true }
  readonly top4Q: { 'top_4Q': true }
  readonly top6Q: { 'top_6Q': true }
  readonly top8Q: { 'top_8Q': true }
  readonly top10Q: { 'top_10Q': true }
  readonly top12Q: { 'top_12Q': true }
  readonly top16Q: { 'top_16Q': true }
  readonly top20Q: { 'top_20Q': true }
  readonly top0cap: { 'top_0cap': true }
  readonly top0p25cap: { 'top_0\.25cap': true }
  readonly top0p5cap: { 'top_0\.5cap': true }
  readonly top0p75cap: { 'top_0\.75cap': true }
  readonly top1cap: { 'top_1cap': true }
  readonly top1p25cap: { 'top_1\.25cap': true }
  readonly top1p5cap: { 'top_1\.5cap': true }
  readonly top2cap: { 'top_2cap': true }
  readonly top2p5cap: { 'top_2\.5cap': true }
  readonly top3cap: { 'top_3cap': true }
  readonly top4cap: { 'top_4cap': true }
  readonly top5cap: { 'top_5cap': true }
  readonly top6cap: { 'top_6cap': true }
  readonly top8cap: { 'top_8cap': true }
  readonly top0ch: { 'top_0ch': true }
  readonly top0p25ch: { 'top_0\.25ch': true }
  readonly top0p5ch: { 'top_0\.5ch': true }
  readonly top0p75ch: { 'top_0\.75ch': true }
  readonly top1ch: { 'top_1ch': true }
  readonly top1p25ch: { 'top_1\.25ch': true }
  readonly top1p5ch: { 'top_1\.5ch': true }
  readonly top2ch: { 'top_2ch': true }
  readonly top2p5ch: { 'top_2\.5ch': true }
  readonly top3ch: { 'top_3ch': true }
  readonly top4ch: { 'top_4ch': true }
  readonly top5ch: { 'top_5ch': true }
  readonly top6ch: { 'top_6ch': true }
  readonly top8ch: { 'top_8ch': true }
  readonly top0cm: { 'top_0cm': true }
  readonly top1cm: { 'top_1cm': true }
  readonly top2cm: { 'top_2cm': true }
  readonly top4cm: { 'top_4cm': true }
  readonly top6cm: { 'top_6cm': true }
  readonly top8cm: { 'top_8cm': true }
  readonly top10cm: { 'top_10cm': true }
  readonly top12cm: { 'top_12cm': true }
  readonly top16cm: { 'top_16cm': true }
  readonly top20cm: { 'top_20cm': true }
  readonly top0dvh: { 'top_0dvh': true }
  readonly top10dvh: { 'top_10dvh': true }
  readonly top20dvh: { 'top_20dvh': true }
  readonly top25dvh: { 'top_25dvh': true }
  readonly top30dvh: { 'top_30dvh': true }
  readonly top33p33dvh: { 'top_33\.33dvh': true }
  readonly top40dvh: { 'top_40dvh': true }
  readonly top50dvh: { 'top_50dvh': true }
  readonly top60dvh: { 'top_60dvh': true }
  readonly top66p67dvh: { 'top_66\.67dvh': true }
  readonly top70dvh: { 'top_70dvh': true }
  readonly top75dvh: { 'top_75dvh': true }
  readonly top80dvh: { 'top_80dvh': true }
  readonly top90dvh: { 'top_90dvh': true }
  readonly top100dvh: { 'top_100dvh': true }
  readonly top0dvw: { 'top_0dvw': true }
  readonly top10dvw: { 'top_10dvw': true }
  readonly top20dvw: { 'top_20dvw': true }
  readonly top25dvw: { 'top_25dvw': true }
  readonly top30dvw: { 'top_30dvw': true }
  readonly top33p33dvw: { 'top_33\.33dvw': true }
  readonly top40dvw: { 'top_40dvw': true }
  readonly top50dvw: { 'top_50dvw': true }
  readonly top60dvw: { 'top_60dvw': true }
  readonly top66p67dvw: { 'top_66\.67dvw': true }
  readonly top70dvw: { 'top_70dvw': true }
  readonly top75dvw: { 'top_75dvw': true }
  readonly top80dvw: { 'top_80dvw': true }
  readonly top90dvw: { 'top_90dvw': true }
  readonly top100dvw: { 'top_100dvw': true }
  readonly top0em: { 'top_0em': true }
  readonly top0p25em: { 'top_0\.25em': true }
  readonly top0p5em: { 'top_0\.5em': true }
  readonly top0p75em: { 'top_0\.75em': true }
  readonly top1em: { 'top_1em': true }
  readonly top1p25em: { 'top_1\.25em': true }
  readonly top1p5em: { 'top_1\.5em': true }
  readonly top2em: { 'top_2em': true }
  readonly top2p5em: { 'top_2\.5em': true }
  readonly top3em: { 'top_3em': true }
  readonly top4em: { 'top_4em': true }
  readonly top5em: { 'top_5em': true }
  readonly top6em: { 'top_6em': true }
  readonly top8em: { 'top_8em': true }
  readonly top0ex: { 'top_0ex': true }
  readonly top0p25ex: { 'top_0\.25ex': true }
  readonly top0p5ex: { 'top_0\.5ex': true }
  readonly top0p75ex: { 'top_0\.75ex': true }
  readonly top1ex: { 'top_1ex': true }
  readonly top1p25ex: { 'top_1\.25ex': true }
  readonly top1p5ex: { 'top_1\.5ex': true }
  readonly top2ex: { 'top_2ex': true }
  readonly top2p5ex: { 'top_2\.5ex': true }
  readonly top3ex: { 'top_3ex': true }
  readonly top4ex: { 'top_4ex': true }
  readonly top5ex: { 'top_5ex': true }
  readonly top6ex: { 'top_6ex': true }
  readonly top8ex: { 'top_8ex': true }
  readonly top0ic: { 'top_0ic': true }
  readonly top0p25ic: { 'top_0\.25ic': true }
  readonly top0p5ic: { 'top_0\.5ic': true }
  readonly top0p75ic: { 'top_0\.75ic': true }
  readonly top1ic: { 'top_1ic': true }
  readonly top1p25ic: { 'top_1\.25ic': true }
  readonly top1p5ic: { 'top_1\.5ic': true }
  readonly top2ic: { 'top_2ic': true }
  readonly top2p5ic: { 'top_2\.5ic': true }
  readonly top3ic: { 'top_3ic': true }
  readonly top4ic: { 'top_4ic': true }
  readonly top5ic: { 'top_5ic': true }
  readonly top6ic: { 'top_6ic': true }
  readonly top8ic: { 'top_8ic': true }
  readonly top0in: { 'top_0in': true }
  readonly top1in: { 'top_1in': true }
  readonly top2in: { 'top_2in': true }
  readonly top4in: { 'top_4in': true }
  readonly top6in: { 'top_6in': true }
  readonly top8in: { 'top_8in': true }
  readonly top10in: { 'top_10in': true }
  readonly top12in: { 'top_12in': true }
  readonly top16in: { 'top_16in': true }
  readonly top20in: { 'top_20in': true }
  readonly top0lh: { 'top_0lh': true }
  readonly top0p25lh: { 'top_0\.25lh': true }
  readonly top0p5lh: { 'top_0\.5lh': true }
  readonly top0p75lh: { 'top_0\.75lh': true }
  readonly top1lh: { 'top_1lh': true }
  readonly top1p25lh: { 'top_1\.25lh': true }
  readonly top1p5lh: { 'top_1\.5lh': true }
  readonly top2lh: { 'top_2lh': true }
  readonly top2p5lh: { 'top_2\.5lh': true }
  readonly top3lh: { 'top_3lh': true }
  readonly top4lh: { 'top_4lh': true }
  readonly top5lh: { 'top_5lh': true }
  readonly top6lh: { 'top_6lh': true }
  readonly top8lh: { 'top_8lh': true }
  readonly top0lvh: { 'top_0lvh': true }
  readonly top10lvh: { 'top_10lvh': true }
  readonly top20lvh: { 'top_20lvh': true }
  readonly top25lvh: { 'top_25lvh': true }
  readonly top30lvh: { 'top_30lvh': true }
  readonly top33p33lvh: { 'top_33\.33lvh': true }
  readonly top40lvh: { 'top_40lvh': true }
  readonly top50lvh: { 'top_50lvh': true }
  readonly top60lvh: { 'top_60lvh': true }
  readonly top66p67lvh: { 'top_66\.67lvh': true }
  readonly top70lvh: { 'top_70lvh': true }
  readonly top75lvh: { 'top_75lvh': true }
  readonly top80lvh: { 'top_80lvh': true }
  readonly top90lvh: { 'top_90lvh': true }
  readonly top100lvh: { 'top_100lvh': true }
  readonly top0lvw: { 'top_0lvw': true }
  readonly top10lvw: { 'top_10lvw': true }
  readonly top20lvw: { 'top_20lvw': true }
  readonly top25lvw: { 'top_25lvw': true }
  readonly top30lvw: { 'top_30lvw': true }
  readonly top33p33lvw: { 'top_33\.33lvw': true }
  readonly top40lvw: { 'top_40lvw': true }
  readonly top50lvw: { 'top_50lvw': true }
  readonly top60lvw: { 'top_60lvw': true }
  readonly top66p67lvw: { 'top_66\.67lvw': true }
  readonly top70lvw: { 'top_70lvw': true }
  readonly top75lvw: { 'top_75lvw': true }
  readonly top80lvw: { 'top_80lvw': true }
  readonly top90lvw: { 'top_90lvw': true }
  readonly top100lvw: { 'top_100lvw': true }
  readonly top0mm: { 'top_0mm': true }
  readonly top1mm: { 'top_1mm': true }
  readonly top2mm: { 'top_2mm': true }
  readonly top4mm: { 'top_4mm': true }
  readonly top6mm: { 'top_6mm': true }
  readonly top8mm: { 'top_8mm': true }
  readonly top10mm: { 'top_10mm': true }
  readonly top12mm: { 'top_12mm': true }
  readonly top16mm: { 'top_16mm': true }
  readonly top20mm: { 'top_20mm': true }
  readonly top0pc: { 'top_0pc': true }
  readonly top1pc: { 'top_1pc': true }
  readonly top2pc: { 'top_2pc': true }
  readonly top4pc: { 'top_4pc': true }
  readonly top6pc: { 'top_6pc': true }
  readonly top8pc: { 'top_8pc': true }
  readonly top10pc: { 'top_10pc': true }
  readonly top12pc: { 'top_12pc': true }
  readonly top16pc: { 'top_16pc': true }
  readonly top20pc: { 'top_20pc': true }
  readonly top0pt: { 'top_0pt': true }
  readonly top1pt: { 'top_1pt': true }
  readonly top2pt: { 'top_2pt': true }
  readonly top4pt: { 'top_4pt': true }
  readonly top6pt: { 'top_6pt': true }
  readonly top8pt: { 'top_8pt': true }
  readonly top10pt: { 'top_10pt': true }
  readonly top12pt: { 'top_12pt': true }
  readonly top16pt: { 'top_16pt': true }
  readonly top20pt: { 'top_20pt': true }
  readonly topN384px: { 'top_-384px': true }
  readonly topN320px: { 'top_-320px': true }
  readonly topN256px: { 'top_-256px': true }
  readonly topN224px: { 'top_-224px': true }
  readonly topN192px: { 'top_-192px': true }
  readonly topN160px: { 'top_-160px': true }
  readonly topN128px: { 'top_-128px': true }
  readonly topN96px: { 'top_-96px': true }
  readonly topN80px: { 'top_-80px': true }
  readonly topN64px: { 'top_-64px': true }
  readonly topN56px: { 'top_-56px': true }
  readonly topN48px: { 'top_-48px': true }
  readonly topN40px: { 'top_-40px': true }
  readonly topN32px: { 'top_-32px': true }
  readonly topN28px: { 'top_-28px': true }
  readonly topN24px: { 'top_-24px': true }
  readonly topN20px: { 'top_-20px': true }
  readonly topN16px: { 'top_-16px': true }
  readonly topN14px: { 'top_-14px': true }
  readonly topN12px: { 'top_-12px': true }
  readonly topN10px: { 'top_-10px': true }
  readonly topN8px: { 'top_-8px': true }
  readonly topN6px: { 'top_-6px': true }
  readonly topN4px: { 'top_-4px': true }
  readonly topN2px: { 'top_-2px': true }
  readonly topN1px: { 'top_-1px': true }
  readonly top0px: { 'top_0px': true }
  readonly top1px: { 'top_1px': true }
  readonly top2px: { 'top_2px': true }
  readonly top4px: { 'top_4px': true }
  readonly top6px: { 'top_6px': true }
  readonly top8px: { 'top_8px': true }
  readonly top10px: { 'top_10px': true }
  readonly top12px: { 'top_12px': true }
  readonly top14px: { 'top_14px': true }
  readonly top16px: { 'top_16px': true }
  readonly top20px: { 'top_20px': true }
  readonly top24px: { 'top_24px': true }
  readonly top28px: { 'top_28px': true }
  readonly top32px: { 'top_32px': true }
  readonly top40px: { 'top_40px': true }
  readonly top48px: { 'top_48px': true }
  readonly top56px: { 'top_56px': true }
  readonly top64px: { 'top_64px': true }
  readonly top80px: { 'top_80px': true }
  readonly top96px: { 'top_96px': true }
  readonly top128px: { 'top_128px': true }
  readonly top160px: { 'top_160px': true }
  readonly top192px: { 'top_192px': true }
  readonly top224px: { 'top_224px': true }
  readonly top256px: { 'top_256px': true }
  readonly top320px: { 'top_320px': true }
  readonly top384px: { 'top_384px': true }
  readonly top0rem: { 'top_0rem': true }
  readonly top0p25rem: { 'top_0\.25rem': true }
  readonly top0p5rem: { 'top_0\.5rem': true }
  readonly top0p75rem: { 'top_0\.75rem': true }
  readonly top1rem: { 'top_1rem': true }
  readonly top1p25rem: { 'top_1\.25rem': true }
  readonly top1p5rem: { 'top_1\.5rem': true }
  readonly top2rem: { 'top_2rem': true }
  readonly top2p5rem: { 'top_2\.5rem': true }
  readonly top3rem: { 'top_3rem': true }
  readonly top4rem: { 'top_4rem': true }
  readonly top5rem: { 'top_5rem': true }
  readonly top6rem: { 'top_6rem': true }
  readonly top8rem: { 'top_8rem': true }
  readonly top0rlh: { 'top_0rlh': true }
  readonly top0p25rlh: { 'top_0\.25rlh': true }
  readonly top0p5rlh: { 'top_0\.5rlh': true }
  readonly top0p75rlh: { 'top_0\.75rlh': true }
  readonly top1rlh: { 'top_1rlh': true }
  readonly top1p25rlh: { 'top_1\.25rlh': true }
  readonly top1p5rlh: { 'top_1\.5rlh': true }
  readonly top2rlh: { 'top_2rlh': true }
  readonly top2p5rlh: { 'top_2\.5rlh': true }
  readonly top3rlh: { 'top_3rlh': true }
  readonly top4rlh: { 'top_4rlh': true }
  readonly top5rlh: { 'top_5rlh': true }
  readonly top6rlh: { 'top_6rlh': true }
  readonly top8rlh: { 'top_8rlh': true }
  readonly top0svh: { 'top_0svh': true }
  readonly top10svh: { 'top_10svh': true }
  readonly top20svh: { 'top_20svh': true }
  readonly top25svh: { 'top_25svh': true }
  readonly top30svh: { 'top_30svh': true }
  readonly top33p33svh: { 'top_33\.33svh': true }
  readonly top40svh: { 'top_40svh': true }
  readonly top50svh: { 'top_50svh': true }
  readonly top60svh: { 'top_60svh': true }
  readonly top66p67svh: { 'top_66\.67svh': true }
  readonly top70svh: { 'top_70svh': true }
  readonly top75svh: { 'top_75svh': true }
  readonly top80svh: { 'top_80svh': true }
  readonly top90svh: { 'top_90svh': true }
  readonly top100svh: { 'top_100svh': true }
  readonly top0svw: { 'top_0svw': true }
  readonly top10svw: { 'top_10svw': true }
  readonly top20svw: { 'top_20svw': true }
  readonly top25svw: { 'top_25svw': true }
  readonly top30svw: { 'top_30svw': true }
  readonly top33p33svw: { 'top_33\.33svw': true }
  readonly top40svw: { 'top_40svw': true }
  readonly top50svw: { 'top_50svw': true }
  readonly top60svw: { 'top_60svw': true }
  readonly top66p67svw: { 'top_66\.67svw': true }
  readonly top70svw: { 'top_70svw': true }
  readonly top75svw: { 'top_75svw': true }
  readonly top80svw: { 'top_80svw': true }
  readonly top90svw: { 'top_90svw': true }
  readonly top100svw: { 'top_100svw': true }
  readonly top0vb: { 'top_0vb': true }
  readonly top10vb: { 'top_10vb': true }
  readonly top20vb: { 'top_20vb': true }
  readonly top25vb: { 'top_25vb': true }
  readonly top30vb: { 'top_30vb': true }
  readonly top33p33vb: { 'top_33\.33vb': true }
  readonly top40vb: { 'top_40vb': true }
  readonly top50vb: { 'top_50vb': true }
  readonly top60vb: { 'top_60vb': true }
  readonly top66p67vb: { 'top_66\.67vb': true }
  readonly top70vb: { 'top_70vb': true }
  readonly top75vb: { 'top_75vb': true }
  readonly top80vb: { 'top_80vb': true }
  readonly top90vb: { 'top_90vb': true }
  readonly top100vb: { 'top_100vb': true }
  readonly top0vh: { 'top_0vh': true }
  readonly top10vh: { 'top_10vh': true }
  readonly top20vh: { 'top_20vh': true }
  readonly top25vh: { 'top_25vh': true }
  readonly top30vh: { 'top_30vh': true }
  readonly top33p33vh: { 'top_33\.33vh': true }
  readonly top40vh: { 'top_40vh': true }
  readonly top50vh: { 'top_50vh': true }
  readonly top60vh: { 'top_60vh': true }
  readonly top66p67vh: { 'top_66\.67vh': true }
  readonly top70vh: { 'top_70vh': true }
  readonly top75vh: { 'top_75vh': true }
  readonly top80vh: { 'top_80vh': true }
  readonly top90vh: { 'top_90vh': true }
  readonly top100vh: { 'top_100vh': true }
  readonly top0vi: { 'top_0vi': true }
  readonly top10vi: { 'top_10vi': true }
  readonly top20vi: { 'top_20vi': true }
  readonly top25vi: { 'top_25vi': true }
  readonly top30vi: { 'top_30vi': true }
  readonly top33p33vi: { 'top_33\.33vi': true }
  readonly top40vi: { 'top_40vi': true }
  readonly top50vi: { 'top_50vi': true }
  readonly top60vi: { 'top_60vi': true }
  readonly top66p67vi: { 'top_66\.67vi': true }
  readonly top70vi: { 'top_70vi': true }
  readonly top75vi: { 'top_75vi': true }
  readonly top80vi: { 'top_80vi': true }
  readonly top90vi: { 'top_90vi': true }
  readonly top100vi: { 'top_100vi': true }
  readonly top0vmax: { 'top_0vmax': true }
  readonly top10vmax: { 'top_10vmax': true }
  readonly top20vmax: { 'top_20vmax': true }
  readonly top25vmax: { 'top_25vmax': true }
  readonly top30vmax: { 'top_30vmax': true }
  readonly top33p33vmax: { 'top_33\.33vmax': true }
  readonly top40vmax: { 'top_40vmax': true }
  readonly top50vmax: { 'top_50vmax': true }
  readonly top60vmax: { 'top_60vmax': true }
  readonly top66p67vmax: { 'top_66\.67vmax': true }
  readonly top70vmax: { 'top_70vmax': true }
  readonly top75vmax: { 'top_75vmax': true }
  readonly top80vmax: { 'top_80vmax': true }
  readonly top90vmax: { 'top_90vmax': true }
  readonly top100vmax: { 'top_100vmax': true }
  readonly top0vmin: { 'top_0vmin': true }
  readonly top10vmin: { 'top_10vmin': true }
  readonly top20vmin: { 'top_20vmin': true }
  readonly top25vmin: { 'top_25vmin': true }
  readonly top30vmin: { 'top_30vmin': true }
  readonly top33p33vmin: { 'top_33\.33vmin': true }
  readonly top40vmin: { 'top_40vmin': true }
  readonly top50vmin: { 'top_50vmin': true }
  readonly top60vmin: { 'top_60vmin': true }
  readonly top66p67vmin: { 'top_66\.67vmin': true }
  readonly top70vmin: { 'top_70vmin': true }
  readonly top75vmin: { 'top_75vmin': true }
  readonly top80vmin: { 'top_80vmin': true }
  readonly top90vmin: { 'top_90vmin': true }
  readonly top100vmin: { 'top_100vmin': true }
  readonly top0vw: { 'top_0vw': true }
  readonly top10vw: { 'top_10vw': true }
  readonly top20vw: { 'top_20vw': true }
  readonly top25vw: { 'top_25vw': true }
  readonly top30vw: { 'top_30vw': true }
  readonly top33p33vw: { 'top_33\.33vw': true }
  readonly top40vw: { 'top_40vw': true }
  readonly top50vw: { 'top_50vw': true }
  readonly top60vw: { 'top_60vw': true }
  readonly top66p67vw: { 'top_66\.67vw': true }
  readonly top70vw: { 'top_70vw': true }
  readonly top75vw: { 'top_75vw': true }
  readonly top80vw: { 'top_80vw': true }
  readonly top90vw: { 'top_90vw': true }
  readonly top100vw: { 'top_100vw': true }
  readonly top0Pct: { 'top_0\%': true }
  readonly top10Pct: { 'top_10\%': true }
  readonly top20Pct: { 'top_20\%': true }
  readonly top25Pct: { 'top_25\%': true }
  readonly top30Pct: { 'top_30\%': true }
  readonly top33p33Pct: { 'top_33\.33\%': true }
  readonly top40Pct: { 'top_40\%': true }
  readonly top50Pct: { 'top_50\%': true }
  readonly top60Pct: { 'top_60\%': true }
  readonly top66p67Pct: { 'top_66\.67\%': true }
  readonly top70Pct: { 'top_70\%': true }
  readonly top75Pct: { 'top_75\%': true }
  readonly top80Pct: { 'top_80\%': true }
  readonly top90Pct: { 'top_90\%': true }
  readonly top100Pct: { 'top_100\%': true }

  // ==================== state ====================
  readonly isDisabled: { 'is-disabled': true }
  readonly isLoading: { 'is-loading': true }
  readonly isActive: { 'is-active': true }
  readonly isFocus: { 'is-focus': true }
  readonly isHover: { 'is-hover': true }
  readonly isSelected: { 'is-selected': true }
  readonly isError: { 'is-error': true }
  readonly isSuccess: { 'is-success': true }
  readonly isWarning: { 'is-warning': true }

  // 允许任意其他原子类
  readonly [key: string]: { [className: string]: true }
}