import {ref} from 'vue';
import "virtual:cssts.css";
import {cssts} from "cssts-ts";
import {csstsAtom} from "virtual:csstsAtom";
defineProps<{ msg: string }>();
const count = ref(0);
const cardStyle = cssts.$cls(csstsAtom.padding20px,csstsAtom.borderRadius8px);
const button$$hover = cssts.$cls(csstsAtom["button$$hover"],csstsAtom.backgroundColorBlue);
const button$$active = cssts.$cls(csstsAtom["button$$active"],csstsAtom.backgroundColorNavy);
const buttonStyle = cssts.$cls(csstsAtom.padding10px,csstsAtom.padding20px,csstsAtom.borderRadius8px,csstsAtom.borderNone,csstsAtom.colorWhite,csstsAtom.fontSizeLarge,csstsAtom.cursorPointer,button$$hover,button$$active);
const linkStyle$$hover = cssts.$cls(csstsAtom["linkStyle$$hover"],csstsAtom.colorDodgerblue);
const linkStyle = cssts.$cls(csstsAtom.colorBlue,linkStyle$$hover);
const codeStyle = cssts.$cls(csstsAtom.padding2px,csstsAtom.padding6px,csstsAtom.borderRadius4px);
const readTheDocs = cssts.$cls(csstsAtom.colorGray);
