/**
 * csstsAtom 核心生成方法
 * 
 * 独立文件，使用 RuntimeStore 避免循环依赖
 */

import { ConfigLookup } from '../config/ConfigLookup'
import { RuntimeStore } from '../store/RuntimeStore'
import Glog from 'glogjs'

// 版本号
const CSSTS_ATOM_CORE_VERSION = '2.2.0'

/**
 * 生成 csstsAtom 对象的 entries 数组
 * 
 * 核心方法，被 generateCsstsAtomModule 和 generateModulesDtsFromStyles 共用
 * 
 * @param styles - 使用的样式集合
 * @param indent - 缩进（JS 用 '  '，DTS 用 '    '）
 * @param suffix - 后缀（JS 不加，DTS 加 ';'）
 * @returns entries 数组
 */
export function generateCsstsAtomEntries(
    styles: Set<string>,
    indent: string = '  ',
    suffix: string = ''
): string[] {
    const prefix = ConfigLookup.classPrefix
    const entries: string[] = []
    const sortedStyles = styles

    for (const name of sortedStyles) {
        // 从初始化的 Map 中获取数据
        const data = RuntimeStore.getRuntimeData(name)

        Glog.info(`执行了判断 ${name}`)

        if (!data) {
            // 不在白名单中，跳过
            Glog.warn(`[generateCsstsAtomEntries] ⚠️ "${name}" 不在 RuntimeStore 中，跳过`)
            continue
        }

        switch (data.group) {
            case 'atom': {
                // 普通原子类：property_value 格式
                const cssClassName = `${prefix}${data.property}_${data.value}`
                entries.push(`${indent}${name}: { '${cssClassName}': '${data.property}' }${suffix}`)
                break
            }
            case 'group': {
                // Group 原子类：name 格式
                const cssClassName = `${prefix}${name}`
                entries.push(`${indent}${name}: { '${cssClassName}': null }${suffix}`)
                break
            }
            case 'pseudo': {
                // 伪类原子类：name 格式，带伪类标记
                const cssClassName = `${prefix}${name}`
                entries.push(`${indent}${name}: { '${cssClassName}': ':${data.pseudo}' }${suffix}`)
                break
            }
            case 'classGroup': {
                // 类组合
                const cssClassName = `${prefix}${name}`
                entries.push(`${indent}${name}: { '${cssClassName}': true }${suffix}`)
                break
            }
        }
    }

    Glog.debug(`[generateCsstsAtomEntries] 输入 ${styles.size} 个，输出 ${entries.length} 个 entries`)
    return entries
}

/**
 * 生成 csstsAtom 模块内容（用于 Vite 虚拟模块）
 */
export function generateCsstsAtomModule(
    styles: Set<string>
): string {
    const lines: string[] = [
        '// Auto-generated by cssts-compiler',
        '',
        'export const csstsAtom = {',
    ]

    // 使用核心方法生成 entries
    const entries = generateCsstsAtomEntries(styles, '  ')

    lines.push(entries.join(',\n'))
    lines.push('}', '', 'export default csstsAtom', '')
    return lines.join('\n')
}

/**
 * 生成虚拟模块的 DTS 声明内容（用于 LSP）
 */
export function generateModulesDtsFromStyles(
    styles: Set<string>
): string {
    // 打印日志：版本号和生成的样式类
    const sortedStyles = [...styles].sort()
    Glog.debug(`[csstsAtomCore v${CSSTS_ATOM_CORE_VERSION}] generateModulesDtsFromStyles`)
    Glog.debug(`  生成 ${styles.size} 个样式类: ${sortedStyles.join(', ')}`)

    const lines: string[] = [
        '/**',
        ' * CSSTS 虚拟模块类型声明（自动生成）',
        ' */',
        '',
        "declare module 'virtual:cssts.css' {}",
        '',
        "declare module 'virtual:csstsAtom' {",
        '  export const csstsAtom: {',
    ]

    // 使用核心方法生成 entries（DTS 需要 4 空格缩进和分号后缀）
    const entries = generateCsstsAtomEntries(styles, '    ', ';')

    lines.push(entries.join('\n'))
    lines.push('  }')
    lines.push('  export default csstsAtom')
    lines.push('}')
    lines.push('')

    const result = lines.join('\n')
    Glog.debug(`[generateModulesDtsFromStyles] 生成的 DTS 内容 (${result.length} 字符):\n${result}`)
    return result
}
